name: First Worklow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Executing Shell Script
              run: |
               chmod +x ascii-script.sh
               ./ascii-script.sh

            - name: List Files
              run: ls -la
      
    second_job:
        runs-on: ubuntu-latest
        steps:
            - name: Sleep
              run: sleep 10

            - name: Display File
              run: cat turtle.txt