name: First Worklow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: List and Read File
              run: |
               echo "These are my files ..."
               ls -la
               cat istio/app01-virtual-service.yaml
            
            - name: Install Cowsay Program
              run: sudo apt install cowsay -y

            - name: Generate ASCII Artwork
              run: cowsay -f dragon "Dragons are cool" >> dragon.txt

            - name: Read File
              run: |
               cat dragon.txt
               ls -la