name: Matrix Workflow

on: 
  push:
  workflow_dispatch:

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        images: [hello-world]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Echo Docker Details
      run: docker info
      
    - name: Run Images
      run: docker run ${{ matrix.images }}