name: Secrets and Variables Workflow

#on: push
on:
    workflow_dispatch:

jobs:
    image_build:
        runs-on: ubuntu-latest
        steps:
        - name: Docker Build
          run: echo docker build -t ${{ vars.CONTAINER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest

        - name: Docker Login
          run: echo docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}

        - name: Docker Publish
          run: echo docker push ${{ vars.CONTAINER_REGISTRY }}/${{ secrets.DOCKER_USERNAME }}/${{ vars.IMAGE_NAME }}:latest